name: first workflow

on:
  push:
    branches:
      - main

jobs:
  first-work-flow:
    name: first
    runs-on: ubuntu-latest
    steps:
      - name: gogo
        run: echo "hello"
        run: echo "fgfg"
        shell: bash
